import type { Metadata } from "next";
import Min_Sans from "next/font/local";
import "./globals.css";

const min_sans = Min_Sans({
  src: "./MinSansVF.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={min_sans.className}>{children}</body>
    </html>
  );
}
